// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4vOGKmVPMBs3m8r6IZCcBpeBfLq_9UW0',
    appId: '1:243827342197:android:62955db615d2e96242313c',
    messagingSenderId: '243827342197',
    projectId: 'eman-smart-panel',
    databaseURL: 'https://eman-smart-panel-default-rtdb.firebaseio.com',
    storageBucket: 'eman-smart-panel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN0-A7EAl5hYxui5YpR3MI_dW4965IYNo',
    appId: '1:243827342197:ios:3e1e774792ee60ed42313c',
    messagingSenderId: '243827342197',
    projectId: 'eman-smart-panel',
    databaseURL: 'https://eman-smart-panel-default-rtdb.firebaseio.com',
    storageBucket: 'eman-smart-panel.appspot.com',
    iosClientId: '243827342197-f58sv2d9gc6alfq5gojae32b9cn1mj3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.emanpanel',
  );
}
